---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность поменять пароль
  - Пользователь должен иметь возможность участвовать в соревнованиях
  - Пользователь должен иметь возможность видеть код своего соперника в режиме он-лайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения
  - При вылете из игры одного из участников, второй должен иметь возможность продолжить играть 
  - При вылете из игры одного из участников, вылетивший игрок может подключиться обратно 
  - Игра не ограничена по времени
  - Кол-во проверок кода во время игры не ограничены
  - При нахождении верного ответа, участником высвечивается модальное окно с победителем 
  - Пользователь должен иметь возможность просматривать таблицу рейтинга 
  - Пользователь должен иметь возможность играть с ботом
  - Пользователь должен иметь возможность приглашать и играть с другом по ссылке

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
  - Пользователь не должен иметь возможность редактирования рейтинга 
  - Пользователь не должен иметь возможность редактирования чужого кода/кода соперника

  
  
