---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру с др. пользователем 
  - Пользователь должен иметь возможность играть без авторизации 
  - Пользователь должен иметь возможность создавать батл


non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
  - Пользователь не должен иметь возможность редактирования рейтинга 
  - Пользователь не должен иметь возможность редактирования чужого кода/кода соперника

  
  
